services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped

    ports:
      - "5678:5678"

    environment:
      - TZ=Asia/Jakarta
      - GENERIC_TIMEZONE=Asia/Jakarta
      - N8N_RUNNERS_ENABLED=true

    volumes:
      - ./n8n_data:/home/node/.n8n

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: always

    ports:
      - "6333:6333"
      - "6334:6334"

    volumes:
      - qdrantdata:/qdrant/storage

  docx_engine:
    build: ./docxtpl_service
    container_name: docx_engine
    restart: unless-stopped
    ports:
      - "8000:8000"

volumes:
  qdrantdata: